apiVersion: v1
kind: Service
metadata:
  name: home-manager-dev-tailscale
  namespace: dev-environment
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "home-manager-dev"
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app: home-manager-dev
  ports:
  - name: ssh
    port: 22
    targetPort: 22
    protocol: TCP
